version: "3.8"
services:
  mysql_container:
    container_name: mysql_container
    build:
      dockerfile: ./docker/mysql/Dockerfile
      args:
        - MYSQL_VERSION=8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "53306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
volumes:
  mysql_volume: